name: QuizMaster3000
main: net.nperkins.quizmaster3000.QuizMaster3000
version: 0.1

commands:
  quiz:
      description: QuizMaster3000
      aliases: [trivia]
      permission: quizmaster3000.quiz
      permission-message: You don't have <permission>
      usage: Type /<command> help for more details!