name: QuizMaster3000
main: net.nperkins.quizmaster3000.QuizMaster3000
version: 0.4.0

commands:
  quiz:
      description: QuizMaster3000
      aliases: [trivia]
      permission: quizmaster3000.quiz
      permission-message: You don't have <permission>
      usage: Type /<command> help for more details!
  quizadmin:
      description: QuizMaster3000 Admin
      aliases: [triviaadmin]
      permission: quizmaster3000.admin
      permission-message: You don't have <permission>
      usage: Type /<command> help for more details!
   
      
permissions:
  quizmaster3000.quiz:
    description: QuizMaster300 Player Commands
    default: true
  quizmaster3000.admin:
    description: QuizMaster300 Admin Commands
    default: op
   